baseurl = "/"
languageCode = "en-us"
title = "康龙公卫"
copyright = "Copyright (c) 2008 - 2017, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-bootstrap"
publishDir = "public"
contentdir = "content"
disqusShortname = "xxxxxx"
googleAnalytics = "UA-XXXXXXX-1"


[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]

    name = "学员名单"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "namelist"
    url = "/page/namelist"

[[menu.main]]

    name = "关于我们"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about"
    url = "/page/about"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = false
